jsonpTest&&jsonpTest({
	"error":0,
	"status":"success",
	"date":"2015-12-09",
	"results":[{
		"currentCity":"北京",
		"pm25":"329",
		"index":[{
			"title":"穿衣",
			"zs":"较冷",
			"tipt":"穿衣指数",
			"des":"建议着厚外套加毛衣等服装。年老体弱者宜着大衣、呢外套加羊毛衫。"
		},
		{
			"title":"洗车",
			"zs":"不宜",
			"tipt":"洗车指数",
			"des":"不宜洗车，未来24小时内有雾，如果在此期间洗车，会弄脏您的爱车。"
		},{
			"title":"旅游",
			"zs":"一般",
			"tipt":"旅游指数",
			"des":"天气较好，温度稍低，加之风稍大，让人感觉有点凉，会对外出有一定影响，外出注意防风保暖。"
		},{
			"title":"感冒",
			"zs":"易发",
			"tipt":"感冒指数",
			"des":"昼夜温差很大，易发生感冒，请注意适当增减衣服，加强自我防护避免感冒。"
		},{
			"title":"运动",
			"zs":"较适宜",
			"tipt":"运动指数",
			"des":"天气较好，但考虑风力较强且气温较低，推荐您进行室内运动，若在户外运动注意防风并适当增减衣物。"
		},{
			"title":"紫外线强度",
			"zs":"中等",
			"tipt":"紫外线强度指数",
			"des":"属中等强度紫外线辐射天气，外出时建议涂擦SPF高于15、PA+的防晒护肤品，戴帽子、太阳镜。"
		}],
		"weather_data":[{
			"date":"周三 12月09日 (实时：3℃)",
			"dayPictureUrl":"http://api.map.baidu.com/images/weather/day/wu.png",
			"nightPictureUrl":"http://api.map.baidu.com/images/weather/night/wu.png",
			"weather":"雾",
			"wind":"微风",
			"temperature":"5 ~ 1℃"
		},{
			"date":"周四",
			"dayPictureUrl":"http://api.map.baidu.com/images/weather/day/qing.png",
			"nightPictureUrl":"http://api.map.baidu.com/images/weather/night/qing.png",
			"weather":"晴","wind":"北风3-4级","temperature":"9 ~ -4℃"
		},{
			"date":"周五",
			"dayPictureUrl":"http://api.map.baidu.com/images/weather/day/qing.png",
			"nightPictureUrl":"http://api.map.baidu.com/images/weather/night/duoyun.png",
			"weather":"晴转多云","wind":"微风","temperature":"5 ~ -4℃"
		},{
			"date":"周六","dayPictureUrl":"http://api.map.baidu.com/images/weather/day/duoyun.png",
			"nightPictureUrl":"http://api.map.baidu.com/images/weather/night/qing.png",
			"weather":"多云转晴",
			"wind":"微风",
			"temperature":"5 ~ -4℃"
		}]
	}]
	})